package com.sah.model;
// Generated 03-jun-2014 21:09:45 by Hibernate Tools 3.2.1.GA



/**
 * Arrendatario generated by hbm2java
 */
public class Arrendatario  implements java.io.Serializable {


     private int idarrendatario;
     private String nombres;
     private String apellidos;
     private int dni;

    public Arrendatario() {
    }

	
    public Arrendatario(int idarrendatario, int dni) {
        this.idarrendatario = idarrendatario;
        this.dni = dni;
    }
    public Arrendatario(int idarrendatario, String nombres, String apellidos, int dni) {
       this.idarrendatario = idarrendatario;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.dni = dni;
    }
   
    public int getIdarrendatario() {
        return this.idarrendatario;
    }
    
    public void setIdarrendatario(int idarrendatario) {
        this.idarrendatario = idarrendatario;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }




}


