package com.sah.model;
// Generated 03-jun-2014 21:09:45 by Hibernate Tools 3.2.1.GA



/**
 * Cuarto generated by hbm2java
 */
public class Cuarto  implements java.io.Serializable {


     private int idcuarto;
     private String caracteristicas;
     private String banio;
     private String restricciones;
     private String estado;

    public Cuarto() {
    }

    public Cuarto(int idcuarto, String caracteristicas, String banio, String restricciones, String estado) {
       this.idcuarto = idcuarto;
       this.caracteristicas = caracteristicas;
       this.banio = banio;
       this.restricciones = restricciones;
       this.estado = estado;
    }
   
    public int getIdcuarto() {
        return this.idcuarto;
    }
    
    public void setIdcuarto(int idcuarto) {
        this.idcuarto = idcuarto;
    }
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public String getBanio() {
        return this.banio;
    }
    
    public void setBanio(String banio) {
        this.banio = banio;
    }
    public String getRestricciones() {
        return this.restricciones;
    }
    
    public void setRestricciones(String restricciones) {
        this.restricciones = restricciones;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


