package com.sah.model;
// Generated 03-jun-2014 21:09:45 by Hibernate Tools 3.2.1.GA



/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private int iddetalle;
     private String objetos;
     private String estado;
     private String cantidad;

    public Detalle() {
    }

    public Detalle(int iddetalle, String objetos, String estado, String cantidad) {
       this.iddetalle = iddetalle;
       this.objetos = objetos;
       this.estado = estado;
       this.cantidad = cantidad;
    }
   
    public int getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(int iddetalle) {
        this.iddetalle = iddetalle;
    }
    public String getObjetos() {
        return this.objetos;
    }
    
    public void setObjetos(String objetos) {
        this.objetos = objetos;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }




}


