package com.sah.model;
// Generated 03-jun-2014 21:09:45 by Hibernate Tools 3.2.1.GA



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private int idhistorial;
     private String calificacion;
     private String comentarios;
     private String recomendacion;

    public Historial() {
    }

    public Historial(int idhistorial, String calificacion, String comentarios, String recomendacion) {
       this.idhistorial = idhistorial;
       this.calificacion = calificacion;
       this.comentarios = comentarios;
       this.recomendacion = recomendacion;
    }
   
    public int getIdhistorial() {
        return this.idhistorial;
    }
    
    public void setIdhistorial(int idhistorial) {
        this.idhistorial = idhistorial;
    }
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public String getRecomendacion() {
        return this.recomendacion;
    }
    
    public void setRecomendacion(String recomendacion) {
        this.recomendacion = recomendacion;
    }




}


