package com.sah.model;
// Generated 31-may-2014 8:42:15 by Hibernate Tools 3.2.1.GA



/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int idReserva;

    public Reserva() {
    }

    public Reserva(int idReserva) {
       this.idReserva = idReserva;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }




}


