package com.sah.model;
// Generated 03-jun-2014 21:09:45 by Hibernate Tools 3.2.1.GA



/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int idreserva;
     private String fecha;
     private String tiempo;
     private String monto;

    public Reserva() {
    }

    public Reserva(int idreserva, String fecha, String tiempo, String monto) {
       this.idreserva = idreserva;
       this.fecha = fecha;
       this.tiempo = tiempo;
       this.monto = monto;
    }
   
    public int getIdreserva() {
        return this.idreserva;
    }
    
    public void setIdreserva(int idreserva) {
        this.idreserva = idreserva;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }




}


