package com.sah.model;
// Generated 03-jun-2014 21:09:45 by Hibernate Tools 3.2.1.GA



/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private int idubicacion;
     private String departamento;
     private String provincia;
     private String distrito;

    public Ubicacion() {
    }

    public Ubicacion(int idubicacion, String departamento, String provincia, String distrito) {
       this.idubicacion = idubicacion;
       this.departamento = departamento;
       this.provincia = provincia;
       this.distrito = distrito;
    }
   
    public int getIdubicacion() {
        return this.idubicacion;
    }
    
    public void setIdubicacion(int idubicacion) {
        this.idubicacion = idubicacion;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }




}


